services:
  cyclopowl-hardware:
    container_name: cyclopowl-hardware
    build:
      context: .
      dockerfile: Dockerfile.production
    volumes:
      - ./:/app/
    network_mode: "host"
    privileged: true # Mandatory to give access to the container to /dev of the host (raspberry pi)
