services:
  cyclopowl-hardware:
    container_name: cyclopowl-hardware
    build: .
    volumes:
      - ./:/app/
    network_mode: "host"
    # devices:
    #   - "/dev/gpiomem:/dev/gpiomem" # Permet l'accès aux GPIO
    privileged: true # Nécessaire pour accéder aux périphériques matériels
